server:
  error:
    # Define as mensagens de erro que serão enviadas ao frontend
    include-stacktrace: on_param # só irá mostrar o stacktrace de erros se o URL contiver ?trace=true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: mysql-dialect
    show-sql: true
#Configurações do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*, prometheus"
#Informações sobre o projeto
info:
  app: "Spring Boot 2 Essentials By DevDojo"
  github: "github.com/Alkhanm"

